### PR TITLE
Bind ESC ESC ESC in all maps

### LINKED ISSUE #12: <ESC> <ESC> <ESC> is unbound
https://www.gnu.org/software/emacs/manual/html_node/elisp/Key-Binding-Conventions.html recommends that "Anything that acts like a temporary mode or state that the user can enter and leave should define `<ESC> <ESC>` or `<ESC> <ESC> <ESC>` as a way to escape."  I find myself hammering either `C-g` or `<ESC>` (I have a mechanical keyboard so it makes appropriate sounds); would be nice if both worked to cancel a transient.

(Aside: I'm happy to see transients arrive!  Starting to convert some of my own stuff to use them.)

### PR DESCRIPTION
**Pull request by tarsius**
Closes #12.

@justbur I imagine this might cause issues for `evil-magit`, could you please check?

### CODE REVIEW

**Comment by justbur** [comment]
I just get `Unbound suffix: '<escape>'...`, so it seems to have no affect. The same is true for the terminal, but that seems weird to me. 

In any case, I don't think this will be a problem for evil-magit, because I evil bindings will be overridden by transient maps.

**Comment by tarsius** [comment]
As a user of Vim bindings you are more of an expert on how to bind `ESC`. I believe `(kbd "ESC")` and `(kbd "<ESC>")` are both correct ways to bind that key (they both give the same result), but I cannot find the documentation. `(kbd "<escape>")` and `[escape]` give a different result, and I think its not what the key labeled `Esc` is supposed to produce. But maybe that is changed somehow when using Evil I wouldn't know.

**Comment by basil-conto** [comment]
I'm not familiar with Vim/Evil key bindings either, and I'm no expert on how Emacs handles/translates/distinguishes between key sequences like `ESC` and `<escape>`, but FWIW the way to handle both variants is by binding `\e` instead. Similarly with `\t` for both `TAB` and `<tab>`, `\r` for both `RET` and `<return>`, etc. See [`(emacs) Init Rebinding`](https://www.gnu.org/software/emacs/manual/html_node/emacs/Init-Rebinding.html), [`(elisp) Basic Char Syntax`](https://www.gnu.org/software/emacs/manual/html_node/elisp/Basic-Char-Syntax.html), and [`(elisp) Key Sequences`](https://www.gnu.org/software/emacs/manual/html_node/elisp/Key-Sequences.html).

Sorry for the noise if this is irrelevant to the discussion.

**Comment by tarsius** [comment]
> `\t` for both `TAB` and `<tab>`

That's not correct (for any of the pairs you have mentioned). `[tab]` is *remapped* to `[\e]`, but they are not the same key. I know because I have fought these remapping in my configuration for years. If the remapping went the other way everything would be peachy. Don't want to go into any more detail than that.

**Comment by basil-conto** [comment]
> That's not correct (for any of the pairs you have mentioned).

Then we're probably miscommunicating.

> `[tab]` is _remapped_ to `[\e]`, but they are not the same key.

I never suggested they are the same.

> Don't want to go into any more detail than that.

Indeed, this is not important.

**Pull request merged**
